CREATE TABLE IF NOT EXIST clientes(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    TELEFEFONO TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
) CREATE TABLE IF NOT EXIST servicion(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    DURACION INTEGER NOT NULL,
    PRECIO INTEGER NOT NULL,
) CREATE TABLE IF NOT EXIST citas(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_cliente INTEGER NOT NULL,
    id_servicio INTEGER NOT NULL,
    FECHA TEXT NOT NULL,
    HORA TEXT NOT NULL,
    PRECIO INTEGER NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id),
    FOREIGN KEY (id_servicio) REFERENCES servicion(id),
)